### ISSUE TITLE
HTML WYSIWYG widget for HTMLTextField is not rendered

### ISSUE THREAD

**Issue by bsnux** [ff0000/scarlet#8]
For models with _scarlet.cms.fields.HTMLTextField_ fields the _WYSIWYG_ widget is not rendered. Instead of it, regular widget for _TextArea_ is rendered.

Partial solution is to override _formfield_for_dbfield_ method and setting _HTMLWidget_ for given field.

**Comment by deserat** [comment]
What version?

**Comment by bsnux** [comment]
Old issue fixed on recent Scarlet versions
